# -*- coding: utf-8 -*-
"""SimpleLinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11UO87OIZ8eHnSFnAvc2PSNSjajhONTrQ
"""

# Import google colab to drive
from google.colab import drive
drive.mount('/content/drive')

# Read dataset and prepare DataFrame from pandas
# df is also like a DataTable
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Salary_dataset.csv')
df = pd.DataFrame(df)

# Displays 1st 5 rows of the df
df.head()

# Display (rows, columns) of df
df.shape

# Data Visualization
# using matplotlib pyplot library, plots Linear Regression chart
import matplotlib.pyplot as plt
plt.plot(df['YearsExperience'], df['Salary'])
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

# Model Prepareation or Model Fitting
# Creates a LinearRegression model using sklearn linear_model
from sklearn.linear_model import LinearRegression
import numpy as np
X = df[['YearsExperience']]
Y = df['Salary']
model = LinearRegression()
model.fit(X,Y)

# Shows intercept and slope y = mx + c
# m -> slope
# c -> intercept
print("intercept", model.intercept_)
print("slope", model.coef_)

# Model Prediction for X in df
y_pred = model.predict(X)
print(y_pred)

# Regression line with pyplot scatterplot
plt.scatter(X,Y,color = 'blue')
plt.plot(X,y_pred,color = 'red')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

# Regression line without pyplot scatterplot
regression_line = model.coef_*X + model.intercept_
plt.scatter(X, Y)
plt.plot(X, regression_line, color='red')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

# Sample Model Prediction for random X
new = [[15]]
new_pred = model.predict(new)
print(new_pred)

# Accuracy is found using sklearn metrics with r2_score
from sklearn.metrics import r2_score
y_pred = model.predict(X)
print("R² =", r2_score(Y, y_pred))

# Sample value prediction for my experience level
my_pred = [[2]]
my_pred_sal = model.predict(my_pred)
print(my_pred_sal)

